myproject/important/filmlist/filmlist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("moviesapp.urls"))
]

myproject/important/filmlist/moviesapp/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static

app_name = 'moviesapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myproject/important/filmlist/moviesapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

myproject/important/filmlist/moviesapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

myproject/important/filmlist/moviesapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from  . models import Movie
# Create your views here.

def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie

    }

    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detais.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return  redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delet.html')

myproject/important/filmlist/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h2>Upload Movies!</h2>
    <br>
    <br>
    <input type="text" name="name" placeholder="Movie name">
    <br>
    <br>
    <input type="text" name="desc" placeholder="Movie description">
    <br>
    <br>
    <input type="text" name="year" placeholder="Movie year">
    <br>
    <br>
    <input type="file" name="img">
    <br>
    <br>
    <input type="submit">


</form>

{% endblock %}

myproject/important/filmlist/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar" href="#">
        <h2>...Movies World..©.</h2>

    </a>
      <ul>
  <li><a class="active" href="#home">Home</a></li>
  <li><a href="#news">Releases</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="#about">About</a></li>
</ul>

  </div>
</nav>
{% block body %}
{% endblock %}
</body>
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover:not(.active) {
  background-color: #111;
}

.active {
  background-color: #04AA6D;
}
</style>
</html>

myproject/important/filmlist/templates/delet.html
<form method="POST">
  {% csrf_token %}
  Sure to delete?
  <input type="submit" value="delete">
</form>

myproject/important/filmlist/templates/detais.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">

        </div>
       <div class="col-md-6">
           {{movie.name}}<br>
           {{movie.desc}}<br>
           {{movie.year}}<br>
           <a class="btn btn-warning" href="{% url 'moviesapp:update' movie.id %}">update</a>
           <br>
           <a class="btn btn-danger" href="{% url 'moviesapp:delete' movie.id %}">Delete</a>

       </div>


    </div>
</div>
{% endblock %}

myproject/important/filmlist/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

myproject/important/filmlist/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}

        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img src="{{i.img.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'moviesapp:detail'  i.id %}" class="btn btn-primary">Explore more</a>
                </div>
            </div>
        </div>
{% endfor %}
    </div>
</div>


{% endblock %}